server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: info
    org:
      springframework:
        boot : info
        security : DEBUG
        web : info

spring:
  batch:
    job:
      enabled: false
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: playplacebucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
