server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: info
    org:
      springframework:
        boot : info
        security : DEBUG
        web : info

