spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playplace?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
    defer-datasource-initialization: true
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600 # 데이터 유지 시간
#      cache-null-values: false # NUll 캐싱 여부
#      host: localhost
#      port: 6379
#      password: ${REDIS_PASSWORD}
